import { StyleSheet } from "react-native";
import Fonts from "@src/theme/fonts";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  btnContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  title: {},
  logo: {
    flex: 1,
    height: 120,
    width: 90,
    alignSelf: "center",
    margin: 30,
  },
  input: {
    height: 48,
    overflow: "hidden",
    borderBottomWidth: 1,
    borderBottomColor: "#3b416124",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  button: {
    backgroundColor: "#3578DB",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  seprator: {
    flex: 1,
    // marginTop: 20,
    justifyContent: "center",
    textAlign: "center",
  },
  socialButton: {
    borderColor: "#3b416124",
    borderWidth: 1,
    backgroundColor: "white",
    paddingLeft: 30,
    paddingRight: 30,
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(0, 0, 0, 0.12)",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 10,
  },
  socialButtonTitle: {
    color: "black",
    fontSize: 16,
    paddingLeft: 10,
    paddingRight: 10,
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontFamily: Fonts.ManropeBold,
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
  },
  footerViewPass: {
    flex: 1,
    marginRight: 30,
  },
  footerText: {
    fontSize: 12,
    color: "rgba(59, 65, 97, 0.54)",
    textAlign: "center",
    paddingTop: 5,
    paddingLeft: 50,
    paddingRight: 50,
    lineHeight: 24,
  },
  footerLink: {
    color: "#3578DB",
    fontWeight: "bold",
    fontSize: 12,
  },
  forgotPassword: {
    color: "#3578DB",
    fontSize: 12,
    flex: 1,
    textAlign: "right",
  },
  headerContainer: {
    flex: 1,
    textAlign: "left",
  },
  header: {
    fontSize: 24,
    textAlign: "left",
  },
});
